name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref}}
          path: .cache
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force